In [1]:
import librosa
import pandas
import numpy
import matplotlib.pyplot as plot
import pathlib
from pathlib import Path
import os
import random
from datetime import datetime
import cv2

In [2]:
def getGenreFromPath(path):
    split_name = str(path.name).split(".")
    return path.parts[-2]
    

In [3]:
data_folder = Path("../../audio/testfiles/GTZAN/genres/")
spectogram_folder = Path("./img_data/")
#duration of songsnippet in seconds
duration = 5 
#matplotlib colormap for spectogram
spectogram_cmap = 'binary' 
#predefined list of genres
pred_genres = 'blues classical country disco hiphop jazz metal pop reggae rock'.split() 
#imagePaths = sorted(list(spectogram_folder.list_images(args["dataset"])))
#imagePaths

In [4]:
#Get directories of all songs
songs = []
genres = []

spectograms = []

for g in data_folder.iterdir():
    genres.append(g.name)
    for i in g.iterdir():
        songs.append(i)

In [5]:
#Calculate all spectograms
cmap = plot.get_cmap(spectogram_cmap)
plot.figure(figsize=(10,10))
spectograms = []

#Iterate through all songs and generate their spactograms. Save them all as images.
for genre in genres:
    pathlib.Path(f'img_data/{genre}').mkdir(parents=True, exist_ok=True)     
for song in songs:
    y, sr = librosa.load(song, mono=True, duration=duration)
    plot.specgram(y, NFFT=2048, Fs=2, Fc=0, noverlap=128, cmap=cmap, sides='default', mode='default', scale='dB');
    plot.axis('off');
    spec_path = pathlib.Path(f'img_data/{getGenreFromPath(song)}/{".".join(str(song.parts[-1]).split(".")[:2])}.png')
    spectograms.append(spec_path)
    plot.savefig(spec_path)
    plot.clf()

/home/carsten/.local/share/virtualenvs/is_music-genre-recognition-7WxnqNEu/lib/python3.7/site-packages/matplotlib/axes/_axes.py:7609: RuntimeWarning: divide by zero encountered in log10
  Z = 10. * np.log10(spec)


<Figure size 720x720 with 0 Axes>

In [6]:
#Seed for RNG
random.seed(datetime.now())

In [7]:
#Shuffle the spectograms
random.shuffle(spectograms)
spectograms

[PosixPath('img_data/country/country.00057.png'),
 PosixPath('img_data/country/country.00026.png'),
 PosixPath('img_data/metal/metal.00089.png'),
 PosixPath('img_data/reggae/reggae.00015.png'),
 PosixPath('img_data/metal/metal.00083.png'),
 PosixPath('img_data/disco/disco.00066.png'),
 PosixPath('img_data/reggae/reggae.00076.png'),
 PosixPath('img_data/reggae/reggae.00045.png'),
 PosixPath('img_data/metal/metal.00020.png'),
 PosixPath('img_data/pop/pop.00069.png'),
 PosixPath('img_data/jazz/jazz.00068.png'),
 PosixPath('img_data/metal/metal.00045.png'),
 PosixPath('img_data/pop/pop.00067.png'),
 PosixPath('img_data/rock/rock.00076.png'),
 PosixPath('img_data/jazz/jazz.00061.png'),
 PosixPath('img_data/hiphop/hiphop.00020.png'),
 PosixPath('img_data/blues/blues.00081.png'),
 PosixPath('img_data/country/country.00044.png'),
 PosixPath('img_data/disco/disco.00002.png'),
 PosixPath('img_data/rock/rock.00011.png'),
 PosixPath('img_data/disco/disco.00095.png'),
 PosixPath('img_data/metal/met

In [14]:
#Import images, convert them to grayscale (one uint8 per pixel) and load them into an array
images = []
for spec_path in spectograms:
    image = cv2.imread(str(spec_path))
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    images.append(gray_image)
images

[array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 25

In [ ]:
labels = []
for spec in spectograms:
    labels.append(spec.parts[-2])
labels